const words = [
    'split',
    'button',
    'calendar',
    'view',
    'field',
    'data',
    'table',
    'color',
    'picker',
    'slider',
    'tree',
    'grid',
    'cell',
    'column',
    'value',
    'record',
    'manager',
    'edit',
    'header',
    'map',
    'tab',
    'iframe',
    'panel',
    'bar',
    'tip',
    'spacer',
    'text',
    'widget',
    'selector',
    'separator',
    'list',
    'menu',
    'progress',
    'pivot',
    'pie',
    'box',
    'bullet',
    'item',
    'fill',
    'saturation',
    'select',
    'hue',
    'alpha',
    'line',
    'discrete',
    'heat',
    'area',
    'upload',
    'component',
    'check',
    'item',
    'container',
    'config',
    'row',
    'cell',
    'range',
    'group',
    'title',
    'slot',
    'tool',
    'trigger',
    'native',
    'toolbar',
    'tristate',
    'preview',
    'up',
    'add',
    'end',
    'click',
    'front',
    'hide',
    'hidden',
    'max',
    'min',
    'show',
    'scrollable',
    'top',
    'left',
    'right',
    'bottom',
    'width',
    'height',
    'item',
    'active',
    'disabled',
    'docked',
    'centered',
    'expand',
    'collapse',
    'pick',
    'tap',
    'node',
    'update',
    'direction',
    'total',
    'cell',
    'double',
    'hold',
    'sort',
    'remove',
    'touch',
    'start',
    'submit',
    'move',
    'insert',
    'complete',
    'dbl',
    'store',
    'built',
    'model',
    'exception',
    'done',
    'leave',
    'enter',
    'mouse',
    'key',
    'down',
    'body',
    'exit',
    'resize',
    'action',
    'success',
    'failed',
    'validity',
    'error',
    'sync',
    'sort',
    'load',
    'drag',
    'drop',
    'over',
    'setup',
    'event',
    'ready',
    'key',
    'query',
    'cls',
    'layout',
    'activate',
    'animation',
    'cancel',
    'swipe', 
    'single',
    'pressed',
    'request',
    'before',
    'after',
    'property',
    'long',
    'create',
    'push',
    'prefetch',
    'sprite',
    'group',
    'extender',
    'change',
    'stop',
    'remove',
    'context',
    'reconfigure',
    'deselect',
    'arrow',
    'center',
    'render',
    'group',
    'restore',
    'save',
    'out',
    'toggle',
    'state',
    'destroy',
    'icon',
    'refresh',
    'close',
    'open',
    'legend',
    'deactivate',
    'indicator',
    'numberer',
    'orientation',
    'disclose',
    'disclosure',
    'interaction',
    'build',
    'rebuild',
    'reload'
].sort((a, b) => a.length - b.length);

const replacements = [
    { find: /^ux/i, replace: 'UX' },
    { find: /^tb/i, replace: 'TB' },
    { find: /d3/gi, replace: 'D3' },
    { find: /mz/gi, replace: 'MZ' },
    { find: /svg/gi, replace: 'SVG' },
    { find: /^url/gi, replace: 'URL' },
    { find: /itemappend/gi, replace: 'ItemAppend' },
    { find: /tofront/gi, replace: 'ToFront' },
    { find: /beforestore/gi, replace: 'BeforeStore' }
];

const strings = new Set();

function camelize(str) {
    str = str.split(/-/).map(capitalize).join('_');

    for (let word of words) {
        str = str.replace(new RegExp(word, 'gi'), capitalize(word));
    }

    for (let replacement of replacements) {
        str = str.replace(replacement.find, replacement.replace);
    }

    strings.add(str);

    return str;
}

function capitalize(str) {
    return str[0].toUpperCase() + str.slice(1);
}

export function toPropName(name) {
    return camelize(name)
}

export function toComponentName(name) {
    return capitalize(camelize(name));
}