rm ext-react/package-lock.json
rm ext-react-babel-plugin/package-lock.json
rm ext-react-classic-boilerplate/package-lock.json
rm ext-react-classic-demo/package-lock.json
rm ext-react-classic-renderwhenready/package-lock.json
rm ext-react-classic-renderwhenready-no-plugin/package-lock.json
rm ext-react-conference-app/package-lock.json
rm ext-react-froala-example/package-lock.json
rm ext-react-gen/package-lock.json
rm ext-react-kitchensink/package-lock.json
rm ext-react-modern-boilerplate/package-lock.json
rm ext-react-modern-demo/package-lock.json
rm ext-react-modern-renderwhenready/package-lock.json
rm ext-react-modern-typescript-boilerplate/package-lock.json
rm ext-react-renderercell/package-lock.json
rm ext-react-rest-example/package-lock.json
rm ext-react-tests/package-lock.json
rm ext-react-transition/package-lock.json
rm ext-webpack-plugin/package-lock.json
rm extjs-to-react-converter/package-lock.json
