rm -r cra-template=ext-react-classic/node_modules
rm -r cra-template=ext-react-modern/node_modules
rm -r ext-react-classic/node_modules
rm -r ext-react-classic-boilerplate/node_modules
rm -r ext-react-classic-demo/node_modules
rm -r ext-react-classic-renderwhenready/node_modules
rm -r ext-react-classic-renderwhenready-no-plugin/node_modules
rm -r ext-react-conference-app/node_modules
rm -r ext-react-froala-example/node_modules
rm -r ext-react-gen/node_modules
rm -r ext-react-kitchensink/node_modules
rm -r ext-react-modern/node_modules
rm -r ext-react-modern-boilerplate/node_modules
rm -r ext-react-modern-demo/node_modules
rm -r ext-react-modern-renderwhenready/node_modules
rm -r ext-react-modern-typescript-boilerplate/node_modules
rm -r ext-react-rest-example/node_modules
rm -r ext-react-tests/node_modules
rm -r extjs-to-react-converter/node_modules
