rm -r ext-react/node_modules
rm -r ext-react-babel-plugin/node_modules
rm -r ext-react-boilerplate/node_modules
rm -r ext-react-classic-boilerplate/node_modules
rm -r ext-react-conference-app/node_modules
rm -r ext-react-demo/node_modules
rm -r ext-react-kitchensink/node_modules
rm -r ext-react-modern-boilerplate/node_modules
rm -r ext-react-rest-example/node_modules
rm -r ext-react-tests/node_modules
rm -r ext-react-typescript-boilerplate/node_modules
rm -r ext-react-webpack-plugin/node_modules
rm -r extjs-to-react-converter/node_modules
rm -r generator-ext-react/node_modules
